// This file is auto-generated by @hey-api/openapi-ts

import type { GetSessionsResponse, CreateSessionResponse, GetHistoryResponse, GetAllKnowledgeResponse, GetKnowledgeResponse } from './types.gen';

const instantSchemaResponseTransformer = (data: any) => {
    data = new Date(data);
    return data;
};

const sessionSchemaResponseTransformer = (data: any) => {
    if (data.createdAt) {
        data.createdAt = instantSchemaResponseTransformer(data.createdAt);
    }
    return data;
};

export const getSessionsResponseTransformer = async (data: any): Promise<GetSessionsResponse> => {
    data = data.map((item: any) => {
        return sessionSchemaResponseTransformer(item);
    });
    return data;
};

export const createSessionResponseTransformer = async (data: any): Promise<CreateSessionResponse> => {
    data = sessionSchemaResponseTransformer(data);
    return data;
};

const chatMessageRecordSchemaResponseTransformer = (data: any) => {
    if (data.timestamp) {
        data.timestamp = instantSchemaResponseTransformer(data.timestamp);
    }
    return data;
};

export const getHistoryResponseTransformer = async (data: any): Promise<GetHistoryResponse> => {
    data = data.map((item: any) => {
        return chatMessageRecordSchemaResponseTransformer(item);
    });
    return data;
};

const knowledgeRecordSchemaResponseTransformer = (data: any) => {
    if (data.createdAt) {
        data.createdAt = instantSchemaResponseTransformer(data.createdAt);
    }
    if (data.lastUpdatedAt) {
        data.lastUpdatedAt = instantSchemaResponseTransformer(data.lastUpdatedAt);
    }
    return data;
};

export const getAllKnowledgeResponseTransformer = async (data: any): Promise<GetAllKnowledgeResponse> => {
    data = data.map((item: any) => {
        return knowledgeRecordSchemaResponseTransformer(item);
    });
    return data;
};

export const getKnowledgeResponseTransformer = async (data: any): Promise<GetKnowledgeResponse> => {
    data = knowledgeRecordSchemaResponseTransformer(data);
    return data;
};
